title: HOKO support
email: support@hokolinks.com
description: HOKO support and documentation center. Everything technical and non-technical about deep linking
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://support.hokolinks.com'
twitter_username: hokolinks
github_username: hokolinks
github_base_url: https://github.com/hokolinks/hoko-docs/tree/master/

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
